### ISSUE TITLE
How to use Broadlink SP3 with IFTTT

### ISSUE THREAD

**Issue by wikijm** [Paxy/IFTTT-broadlink-milight-smart#1]
Hi,

Could you create a little HOWTO concerning usage of Broadlink SP3 with IFTTT, please?
Thanks in advance.

P.S : If you want to propose a french translation, I'm in!

**Comment by Paxy** [comment]
Similar to following procedure but with URL to your Python script.
https://m.youtube.com/watch?v=OH9Xo7F6g2M

**Comment by wikijm** [comment]
Thanks for your really fast answer :-)

I'll check video later, and reopen issue if needed.
